package view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

import interface_adapter.class_average.ClassAverageController;
import interface_adapter.class_average.ClassAverageState;
import interface_adapter.class_average.ClassAverageViewModel;
import interface_adapter.logged_in.LoggedInController;

/**
 * View for showing class average and grade distribution of an assignment.
 */
public class ClassAverageView extends JPanel implements ActionListener, PropertyChangeListener {

    public static final int WIDTH = 600;
    public static final int HEIGHT = 300;
    public static final String SELECT = "Select an Assignment";
    public static final String ROUNDING = "%.1f";

    private final String viewName = "average";

    private final ClassAverageViewModel classAverageViewModel;

    private ClassAverageController classAverageController;
    private LoggedInController loggedInController;

    private JComboBox<String> assignmentComboBox;

    private JLabel studentsLabel;
    private JLabel meanLabel;
    private JLabel medianLabel;
    private JLabel stdDevLabel;

    private JPanel chartPanel;

    private JLabel myScoreLabel;
    private JButton backButton;

    public ClassAverageView(ClassAverageViewModel viewModel) {
        this.classAverageViewModel = viewModel;
        this.classAverageViewModel.addPropertyChangeListener(this);

        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

        final JPanel topRow = new JPanel();
        topRow.setLayout(new FlowLayout(FlowLayout.LEFT));

        assignmentComboBox = new JComboBox<>();
        assignmentComboBox.addItem(SELECT);

        assignmentComboBox.addActionListener(event -> {
            final String selected = (String) assignmentComboBox.getSelectedItem();
            if (selected != null && !selected.equals(SELECT)) {
                classAverageController.execute(false, selected);
            }
        });

        topRow.add(assignmentComboBox);

        final JPanel statsRow = new JPanel();
        statsRow.setLayout(new FlowLayout(FlowLayout.CENTER));

        studentsLabel = new JLabel("Students: ");
        meanLabel = new JLabel("   Mean: ");
        medianLabel = new JLabel("   Median: ");
        stdDevLabel = new JLabel("   Std. Dev.: ");

        statsRow.add(studentsLabel);
        statsRow.add(meanLabel);
        statsRow.add(medianLabel);
        statsRow.add(stdDevLabel);

        final JPanel bottomRow = new JPanel();
        bottomRow.setLayout(new BorderLayout());

        myScoreLabel = new JLabel("My Score: ");
        bottomRow.add(myScoreLabel, BorderLayout.WEST);

        backButton = new JButton("Back");
        bottomRow.add(backButton, BorderLayout.EAST);

        backButton.addActionListener(this);

        this.add(topRow);
        this.add(statsRow);
        this.add(createChartPanel());
        this.add(bottomRow);
    }

    private JPanel createChartPanel() {
        chartPanel = new JPanel();
        chartPanel.setLayout(new BorderLayout());
        chartPanel.setPreferredSize(new Dimension(WIDTH, HEIGHT));
        return chartPanel;
    }

    /**
     * Handles back button click events within the Class Average view.
     *
     * @param event the action event generated by back button
     */
    public void actionPerformed(ActionEvent event) {
        if (event.getSource().equals(backButton)) {
            classAverageController.execute(true, "");
        }
    }

    /**
     * Handles updates from ClassAverageViewModel when its state changes.
     *
     * @param evt the property change event containing the new ClassAverageState
     */
    public void propertyChange(PropertyChangeEvent evt) {
        if ("state".equals(evt.getPropertyName())) {

            final ClassAverageState state = (ClassAverageState) evt.getNewValue();

            if (state.getAssignmentNames() != null) {
                assignmentComboBox.removeAllItems();
                assignmentComboBox.addItem(SELECT);
                for (String name : state.getAssignmentNames()) {
                    assignmentComboBox.addItem(name);
                }
            }

            studentsLabel.setText("Students: " + state.getStudentCount());
            meanLabel.setText("   Mean: " + String.format(ROUNDING, state.getMean()));
            medianLabel.setText("   Median: " + String.format(ROUNDING, state.getMedian()));
            stdDevLabel.setText("   Std. Dev.: " + String.format(ROUNDING, state.getStdDev()));

            myScoreLabel.setText("My Score: " + state.getMyScore());

            if (state.getChartPanel() != null) {
                chartPanel.removeAll();
                chartPanel.add(state.getChartPanel(), BorderLayout.CENTER);
                chartPanel.revalidate();
                chartPanel.repaint();
            }
        }
    }

    public String getViewName() {
        return viewName;
    }

    public void setClassAverageController(ClassAverageController classAverageController) {
        this.classAverageController = classAverageController;
    }

    public void setLoggedInController(LoggedInController loggedInController) {
        this.loggedInController = loggedInController;
    }
}
